# Generated by Django 5.1.7 on 2025-03-19 15:17

import apps.users.entities.users
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Администратор', 'Администратор'), ('Покупатель', 'Покупатель'), ('Продавец', 'Продавец'), ('Тех .поддержка', 'Тех .поддержка')], default=apps.users.entities.users.UserRole['CUSTOMER'], max_length=256, verbose_name='Роль'),
        ),
    ]
