# Generated by Django 5.1.7 on 2025-04-01 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enters_count',
            field=models.BigIntegerField(default=0, verbose_name='Количество входов'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Администратор', 'Администратор'), ('Покупатель', 'Покупатель'), ('Продавец', 'Продавец'), ('Тех .поддержка', 'Тех .поддержка')], max_length=256, verbose_name='Роль'),
        ),
        migrations.CreateModel(
            name='BlacklistToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jti', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('is_revoked', models.BooleanField(default=False)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Issued token',
                'verbose_name_plural': 'Issued tokens',
            },
        ),
    ]
