# Generated by Django 5.1.7 on 2025-04-01 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_enters_count_alter_user_role_blacklisttoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlacklistToken',
        ),
    ]
