# Generated by Django 5.1.7 on 2025-04-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_blacklisttoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удален'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Администратор', 'Администратор'), ('Покупатель', 'Покупатель'), ('Продавец', 'Продавец'), ('Тех.поддержка', 'Тех.поддержка')], max_length=256, verbose_name='Роль'),
        ),
    ]
