# Generated by Django 5.1.7 on 2025-04-11 14:37

import apps.users.models.organizations
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название организации')),
                ('documents', models.FileField(help_text='Загрузите документы организации в формате PDF', upload_to=apps.users.models.organizations.organization_documents_upload_path, verbose_name='Документы (PDF)')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
    ]
