# Generated by Django 5.1.7 on 2025-04-28 14:36

import apps.users.models.organizations
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='documents',
        ),
        migrations.CreateModel(
            name='OrganizationDocument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.users.models.organizations.organization_documents_upload_path, verbose_name='Документ (PDF)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='users.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Документ организации',
                'verbose_name_plural': 'Документы организаций',
            },
        ),
    ]
