# Generated by Django 5.1.7 on 2025-04-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_main_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='main_category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='characteristic',
            options={},
        ),
        migrations.AlterModelOptions(
            name='characteristicoption',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.RemoveField(
            model_name='characteristic',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='characteristics',
            field=models.ManyToManyField(related_name='categories', to='products.characteristic', verbose_name='Характеристики'),
        ),
        migrations.AddField(
            model_name='product',
            name='seller_id',
            field=models.CharField(default='default_seller', max_length=255, verbose_name='ID продавца'),
        ),
        migrations.DeleteModel(
            name='MainCategory',
        ),
    ]
