# Generated by Django 5.1.7 on 2025-04-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_category_main_category_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller_id',
            field=models.CharField(max_length=255, verbose_name='ID продавца'),
        ),
    ]
